### PR TITLE
Ts testing support

### PR DESCRIPTION
**Pull request by BugsBunnyBR**
This pull request adds support to lint usint tslint, unit test with karma and e2e test using protractor.
All the work here is done by @lathonez in his [clicker](https://github.com/lathonez/clicker) repo.
Note: I made all lint tests pass by disabling lots of it, ionic team can set it as they want.
This is related to : https://github.com/driftyco/ionic/issues/5579

### CODE REVIEW

**Comment by tlancina** [comment]
Awesome, thanks for the PR! Holy dependencies :)

Just a heads up, the build changes are still being finalized, so this may sit for a bit until we have a good story on how to start Ionic projects.  Related: https://github.com/driftyco/ionic-cli/issues/845.

**Comment by BugsBunnyBR** [comment]
I think some dependencies may be removed, since the real MVP is @lathonez, he can help to strip that down.

**Comment by lathonez** [comment]
There shouldn't be any that are redundant, but depending on the functionality that you want to keep in. chalk is a quick win as it's just logging. Happy to be involved in work to strip stuff out when you come to merge it.

**Comment by danbucholtz** [comment]
Hi @BugsBunnyBR,

Wow, this is awesome!  Nice work!  Unfortunately at this time, we decided as a team not to merge this because all of the build stuff is in flux with our move to AoT compiling.  We are going to leverage the Angular-CLI's set-up for karma and protractor as well.

We sincerely appreciate your contribution and hope you'll contribute again.  Things will hopefully slow down for us soon so we can respond to these matters in a more timely fashion.  Thank you so much for being a member of our community and putting in the great work!!

Thanks,
Dan

**Pull request closed without merging**
