### PR TITLE
Store login state in local storage

### PR DESCRIPTION
**Pull request by 3dd13**
this is a modified version of Pull Request https://github.com/driftyco/ionic-conference-app/pull/111

- login state is stored in local storage
- login state changes are broadcast via Ionic Events
- side menu items visibilities are changed when login state changes events are received

### CODE REVIEW

**Comment by brandyscarney** [comment]
Thank you for the PR! This is awesome. :)

**Comment by alvarosanchez** [comment]
I can't run the application after this merge, it throws this at startup:

```
TypeError: Cannot read property 'user:login' of undefined
    at Events.subscribe (app.bundle.js:41672)
    at ConferenceApp.listenToLoginEvents (app.bundle.js:3265)
```

Using `2.0.0-beta.17`.

**Comment by 3dd13** [comment]
@alvarosanchez 

there is an issue in current "published" version in ionic-framework v2 events class:
https://github.com/3dd13/ionic/commit/c05d19606affd35cadac63a668606489019530af

it has been fixed in latest ionic 2.0 branch:
https://github.com/driftyco/ionic/commit/141404f973cdd8bb10d01392e918f486c1218cfa

should be available later when the next release is published to npm and then the ionic-framework dependency version is bumped

**Comment by alvarosanchez** [comment]
:+1:

**Pull request merged**
